blog/urls.py
from django.urls import path
from .views import render_post, post_detail

app_name = 'blog' 

urlpatterns =[
    path('', render_post, name='post'),
    path('<int:post_id>', post_detail, name= 'post_detail')
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf.urls.static import static
from django.conf import settings

from portfolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls'))

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.db.models.fields import CharField
from django.db.models.fields.files import ImageField
import datetime

# Create your models here.
class Post(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to='blog/images/')
    date = models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField

class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to='portfolio/images/')
    url = URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
# Create your views here.

def render_post(request):
    posts = Post.objects.all()
    return render(request, 'post.html', {'posts': posts})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {'post': post})

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.

def home(request):
    projects = Project.objects.all()

    return render(request, 'home.html', {'projects': projects})

blog/templates/post.html
{% extends 'layout.html'%}

{% block content %}


<h1>Posts</h1>

{% for post in posts %}
<div class="p-3">
 <div class="card card-body bg-black">
    <div class="row">
        <div class="col-3">
            <img src="{{post.image.url}}" class="img-fluid"/> 
        </div>
        <div class="col-9">
            <h2>{{post.title}}</h2>
                <p>{{post.description|truncatechars:90}}</p>
                <p>{{post.date|date:'M d Y'|upper}}</p>
                
                <a href="{% url 'blog:post_detail' post.id %}" class = 'btn btn-primary' >Mas informacion</a>
        </div>
    </div>
 </div>
</div>
{% endfor %}
<div class="text-center">
{% endblock %}
</div>

blog/templates/post_detail.html
{% extends 'layout.html'%}

{% block content %}
<div class="text-center">
    
    <h2>{{post.title}}</h2>
    <h3 class =  'my-2 h5 text-muted'>{{post.date|date:'F jS Y'}}</h3>

    <img src="{{post.image.url}}" class="img-fluid">  
    <div class="my-4">
        <p>{{post.description}}</p>
    </div>
</div>




<div class="text-center">
    {% endblock %}
    </div>

portfolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}
    <header class="row bg-black" >
        <div class="col-md-4">
            <img src="{% static 'portfolio/b9f9ca89dca8a90769665656ff4278a9.jpg' %} " style="max-width:96%" alt="...">
        </div>
        <div class="col-md-8 my-auto">
            <h1>I am <strong>Samuel</strong></h1>
            <h3>
                I am a python developer
            </h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut id tristique ex, et condimentum elit. 
                Vestibulum euismod massa ut massa finibus, vitae lobortis lectus tristique. Suspendisse suscipit 
                volutpat magna a pellentesque. Vestibulum vel pulvinar sapien. Ut porttitor justo nunc. Donec volutpat 
                ut dui ac auctor. Fusce sagittis mi eget metus venenatis cursus. Donec scelerisque, tellus eu mattis fringilla, 
                ex ex bibendum augue, nec eleifend dui lorem ut mi. Nam quis sem eget quam semper cursus. Vivamus pellentesque pharetra 
                augue vitae dapibus. Sed laoreet sem in sem venenatis, at cursus nisl scelerisque. Nullam feugiat sem quis dapibus lobortis. 
                Nam varius volutpat.</p>
                <a href="{% static 'portfolio/SamuelCV.pdf'%}" class="btn btn-primary btn-lg rounded-0 my-3">Download CV</a>
        </div>
        
    </header>
    
<div class="row my-4 text-center">

     <h3> My Projects </h3>   
     <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam non.</p>

    {% for project in projects %}

        <div class = 'col-md-4 p-4'> 
            <div class="card bg-black card-project">
                <img src="{{project.image.url}} " class="card-img-top" />  
                <div class="card-body text-light">
                    <h2>{{ project.title }}</h2>
                    <p>{{project.description}}</p>     
                    <a href="{{project.url}}" class = 'btn btn-light rounded-0 btn-sm' target="_blank">{{project.url}}</a>      
                    
                </div>
            </div>
        </div>
        

        {% endfor %}
{% endblock %}
</div>

portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="text-light">

    {% include 'partials/navbar.html'%}

    <div class="container p-4">
        {% block content %}

        {% endblock %}
        <hr>
    </div>
   
    <footer class="navbar-brand fw-bold fst-italic">Footer</footer>
</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="/" >Portafolio</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:post' %}">Blog</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% static 'portfolio/SamuelCV.pdf'%}" target="_blank">Download CV</a>
          </li>
  
        </ul>
      </div>
    </div>
  </nav>